### PR TITLE
Added localization system and Spanish (es) strings

### PR DESCRIPTION
**Pull request by Roboe**
Implemented the use of Android resource framework to provide localized strings.
Only code change needed was passing a Context object as parameter on MobileDataStatusReceiver.getNetworkOperatorAndServiceProvider() to get "unknown network".

Hope I didn't mess up anything.
Running on my mako (Nexus 4) on Android 4.4.4 without any trouble.

### CODE REVIEW

**Comment by ultrafunk** [comment]
The changes will be checked and merged as soon as time is available for the task. If they are all good, an updated version of the widget will be published/released shortly after that. Thanks for your contribution!

**Comment by Roboe** [comment]
Perfect, take your time, :)

I just discovered an issue, trying on a condor (Moto E): On activity_config.xml, bgTransTextView overlaps bgTransValTextView when the first one contains a large string (like on my translation).
I forgot how Android layouts work, but I can take a look whether you want.

Thanks for your reception! :+1:

**Comment by ultrafunk** [comment]
Version 1.5.4. has now been published on Google Play. The layout issues you mentioned in activity_config.xml should now be fixed, please let me know if there is anything that needs adjusting, I have only done limited testing with the Spanish translation activated in Android.

**Comment by Roboe** [comment]
Great! No bugs, so far.

One last thing; I discovered NetInfo from [F-Droid Store](https://f-droid.org/repository/browse/?fdfilter=netinfo&fdid=com.ultrafunk.network_info), but I don't know _yet_ how updates are pushed to their repos, since they manage the builds with a bot... How can I/we request an update?

Thanks for the fastness, :)

**Comment by ultrafunk** [comment]
If you have the time, there are some new strings in version 1.6.0 that needs to be translated (the last four): https://github.com/ultrafunk/netinfo/blob/master/NetInfo_Widget/src/main/res/values-es/strings.xml

**Pull request merged**
